openapi: 3.0.0
info:
  title: Code Improve API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0 
  

servers:
  - url: https://localhost:30005

paths:
  /api/register/user:
    post:
      summary: Create the user
      description: Create a new user in the system.
      tags:
       - UserController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                password:
                  type: string
                  description: The password of the user
              required:
                - username
                - password
      responses:
        201:
          description: User created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the user.
    
  /api/login/user:
    post:
      summary: login the user
      description: Authenticate the user .
      tags:
       - UserController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                password:
                  type: string
                  description: The password of the user
              required:
                - username
                - password
      responses:
        201:
          description: User created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the user.
        
  
            

        